apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kfserving-test
  annotations:
     serving.kubeflow.org/s3-endpoint: s3-eu-central-1.amazonaws.com
     serving.kubeflow.org/s3-usehttps: "1"
     serving.kubeflow.org/s3-verifyssl: "1"
     serving.kubeflow.org/s3-region: eu-central-1
type: Opaque
stringData:
# KFServing 0.4
  AWS_ACCESS_KEY_ID: <your key id>
  AWS_SECRET_ACCESS_KEY: <your access key>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: kfserving-test
secrets:
  - name: aws-secret